ALTER TABLE caso_evento DROP CONSTRAINT IF EXISTS ck_caso_evento_tipo;

ALTER TABLE caso_evento
  ADD CONSTRAINT ck_caso_evento_tipo CHECK (tipo_evento IN (
    'INICIO_PROCESO','AVANCE_ETAPA','ENVIAR_ETAPA','REPETICION_ETAPA','CIERRE_PROCESO',
    'PAUSA_PROCESO','REANUDAR_PROCESO',
    'COMPROMISO_REGISTRADO','ACTUALIZAR_COMPROMISO','RENOVAR_COMPROMISO',
    'COMPROMISO_INCUMPLIDO','CAMBIO_PARAMETRO','OBSERVACION','OBSERVACION_ETAPA'
  ));
