package pe.morosos.seguimiento.entity;

public enum CasoEventoTipo { INICIO_PROCESO, AVANCE_ETAPA, REPETICION_ETAPA, CIERRE_PROCESO, COMPROMISO_REGISTRADO, COMPROMISO_INCUMPLIDO, CAMBIO_PARAMETRO, OBSERVACION }
