package pe.morosos.seguimiento.entity;

public enum CasoEventoTipo {
    INICIO_PROCESO,
    AVANCE_ETAPA,
    REPETICION_ETAPA,
    CIERRE_PROCESO,
    PAUSA_PROCESO,
    REANUDAR_PROCESO,
    COMPROMISO_REGISTRADO,
    ACTUALIZAR_COMPROMISO,
    RENOVAR_COMPROMISO,
    COMPROMISO_INCUMPLIDO,
    CAMBIO_PARAMETRO,
    OBSERVACION
}
