app:
  security:
    jwt:
      issuer: ${JWT_ISSUER:http://localhost:8080}
      audience: ${JWT_AUDIENCE:morosos-app}
      secret: ${JWT_SECRET:3HugO1JOjAKmVZYTMKO6NqWGqvTJ5xO41wiBWyqnuAnDgwo2RrUVqpOJ4I4kWjzyMfBLTWUjw3UV0VeXkjWOpA}
