spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/morosos_test
    username: morosos_test
    password: morosos_test
  jpa:
    show-sql: false

app:
  security:
    jwt:
      issuer: http://localhost:8080
      audience: morosos-app
      secret: 3HugO1JOjAKmVZYTMKO6NqWGqvTJ5xO41wiBWyqnuAnDgwo2RrUVqpOJ4I4kWjzyMfBLTWUjw3UV0VeXkjWOpA
